---
title: "composition analysis"
author: "Daniel Perez"
date: "04/08/2022"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(epiextractr)
library(epidatatools)
library(labelled)
library(here)
library(blsAPI)
library(openxlsx)
library(MetricsWeighted)
library(gtools)
library(statar)
```


```{r Load CPS}
cpi <- read_csv(here("input/cpi_annual.csv")) 
cpi_base <- cpi$cpiurs[cpi$year == 2019] 

cpsorg <-load_org(1994:2019, year, month, orgwgt, age, emp, lfstat, selfemp, selfinc, hourslw1, hoursu1i, hoursuorg, hoursut, hoursvary, wage, weekpay) %>%
  filter(age>=16, emp %in% c(0,1)) %>%
  mutate(wgt = orgwgt/12) %>% 
  #create new version of selfemp/selfinc to exclude self employer workers
  mutate(selfemp0 = ifelse(selfemp==1 & !is.na(selfemp), yes=1, no=0),
         selfinc0 = ifelse(selfinc==1 & !is.na(selfinc), yes=1, no=0),
         hoursvary0 = ifelse(hoursvary==1 & !is.na(hoursvary), yes=1, no=0)) %>% 
  filter(selfemp0==0, selfemp0==0) %>% 
  #Merge CPI-U-RS data
  left_join(cpi, by='year') %>% 
  mutate(hours = hoursut) %>% 
  mutate(hours = replace(hours, emp==0, 0), #Assign unemp/NILF workers 0 hours
         realwage = wage*(cpi_base/cpiurs), # inflation adjust wages to 2019$
         realweekpay = weekpay *(cpi_base/cpiurs),
         #create indicators for positive hours, weekly pay, and wages
         pwages = ifelse(realwage>0 & !is.na(realwage) , yes=1, no=0), 
         pweekpay = ifelse(realweekpay>0 & !is.na(realweekpay) , yes=1, no=0), 
         phours1 = ifelse(hours>0 & !is.na(hours), yes=1, no=0)) %>%
  set_value_labels(pwages = c('Positive wages' = 1, 'Zero wages' = 0),
                   pweekpay = c('Positive weekpay' = 1, 'Zero weekpay' = 0),
                   phours1 = c('Positive hours, primar' = 1, 'Zero hours' =0))
```

```{r avg hours wages and pay for employed}

emp_cuts_alljobs <- cpsorg %>% 
  filter(emp==1, pweekpay==1) %>% 
  group_by(year) %>% 
  summarize(avg_realwage = weighted.mean(realwage, w=wgt, na.rm=TRUE),
            avg_hours_total = weighted.mean(hoursut, w=wgt, na.rm=TRUE),
            avg_realweekpay = weighted.mean(realweekpay, w=wgt)) %>%
  mutate(diff = avg_realwage *avg_hours_total) %>% 
  write.xlsx(here('data/emp_cuts_hourstotal.xlsx'))
  

emp_cuts <- cpsorg %>% 
  #all employed workers with positive weekly pay
  filter(emp==1, pweekpay==1) %>% 
  group_by(year) %>% 
  summarize(avg_realwage = weighted.mean(realwage, w=wgt, na.rm=TRUE),
            avg_hours_tot = weighted.mean(hours, w=wgt, na.rm=TRUE),
            avg_realweekpay = weighted.mean(realweekpay, w=wgt)) %>%
  mutate(avg_wageXhours = avg_realwage * avg_hours_tot,
         diff = avg_realweekpay - avg_wageXhours)
  write.xlsx(here('data/emp_cuts.xlsx'))

test<- cpsorg %>% 
  filter(emp==1) %>% 
  mutate(across(phours1|pwages|pweekpay, ~to_factor(.x))) %>% 
  count(phours1,pwages,pweekpay)


```


As a note, we want to remove self employed / self incorporated folks because they do not report wages / hours despite being employed. We do want to keep non-self emp/inc folks though, including those who are just NILF or selfemp/selfinc==NA, because we want to turn them into NILF workers with zero wages/hours

```{r Quintile and Median analysis}

set.seed(1017)

cps_filtered <- cpsorg %>% 
  filter(age<65) %>% 
  filter((emp==1 & phours1== 1 & pweekpay==1) | (emp==0 & phours1==0 & pweekpay==0)) %>% 
  mutate(index = runif(nrow(.), min = 0, max=1)) %>%  #assign each observation a random # between 0 and 1
  arrange(year, realweekpay, index) %>%  # sort by year, real weekly pay, and index (might be unnecessary)?
  group_by(year) %>% 
  mutate(cumsum = cumsum(orgwgt/12), #column with cumulative sum of org weight
         pop = sum(orgwgt/12), #column with total pop in each year
         quint_pop = pop/5, # 1/5th of the weighted population by year
         med_pop = pop/2) %>% # 1/2 of weighted pop by year
  mutate(quint_bins = ifelse(cumsum <= quint_pop, 1,
                       ifelse(cumsum > quint_pop & cumsum <= quint_pop*2, 2,
                              ifelse(cumsum > quint_pop*2 & cumsum <= quint_pop*3, 3,
                                     ifelse(cumsum > quint_pop*3 & cumsum <= quint_pop*4, 4, 5))))) %>% 
  mutate(med_bins = ifelse(cumsum <= med_pop, yes=1, no=2)) %>% 
  ungroup()

quint_cutoffs <- cps_filtered %>% 
  group_by(year, quint_bins) %>% 
  summarize(avg_weekpay_cutoff = max(realweekpay)) %>% 
  pivot_wider(id_cols = year, names_from = quint_bins, values_from = avg_weekpay_cutoff)

med_cutoffs <- cps_filtered %>% 
  group_by(year, med_bins) %>% 
  summarize(avg_weekpay_cutoff = max(realweekpay)) %>% 
  pivot_wider(id_cols = year, names_from = med_bins, values_from = avg_weekpay_cutoff)
  

quintile_metrics <- cps_filtered %>% 
  group_by(year, quint_bins) %>% 
  summarize(avg_weekpay = weighted.mean(realweekpay, w=wgt),
            epop = weighted.mean(emp, w=wgt),
            avg_hours = weighted.mean(hours, w=wgt),
            avg_wage = weighted.mean(realwage, w=wgt),
            n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  pivot_wider(id_cols = year, names_from = quint_bins, values_from = c(avg_wage, avg_hours, avg_weekpay, epop, n, wgt_n))


median_metrics <- cps_filtered %>% 
  group_by(year, med_bins) %>% 
  summarize(avg_weekpay = weighted.mean(realweekpay, w=wgt),
            epop = weighted.mean(emp, w=wgt),
            avg_hours = weighted.mean(hours, w=wgt),
            avg_wage = weighted.mean(realwage, w=wgt),
            n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  pivot_wider(id_cols = year, names_from = med_bins, values_from = c(avg_wage, avg_hours, avg_weekpay, epop, n, wgt_n))

```

```{r Workbook export}

rand_order <- createWorkbook()

pct = createStyle(numFmt = '0.0%')
acct = createStyle(numFmt = '#,#0.0')
currency = createStyle(numFmt = '$#,#0.00') 
hs2 <- createStyle(fgFill = "#bfbfbf", halign = "CENTER", textDecoration = "Bold",
                   border = "Bottom", fontColour = "black")

addWorksheet(rand_order, sheetName = "Quintile metrics")
addWorksheet(rand_order, sheetName = "Median metrics")
addWorksheet(rand_order, sheetName = "Quint cutoffs")
addWorksheet(rand_order, sheetName = "Median cutoffs")


writeData(rand_order, quintile_metrics, headerStyle = hs2, sheet = "Quintile metrics", startCol = 1, startRow = 1, colNames = TRUE)
writeData(rand_order, median_metrics, headerStyle = hs2, sheet = "Median metrics", startCol = 1, startRow = 1, colNames = TRUE)
writeData(rand_order, quint_cutoffs, headerStyle = hs2, sheet = "Quint cutoffs", startCol = 1, startRow = 1, colNames = TRUE)
writeData(rand_order, med_cutoffs, headerStyle = hs2, sheet = "Median cutoffs", startCol = 1, startRow = 1, colNames = TRUE)

# #Currency format
# addStyle(rand_order, "Quintile metrics", style=currency, cols=c(2:27,80:105), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
# addStyle(rand_order, "Median metrics", style=currency, cols=c(2:27,80:105), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)
# 
# #Percent format
# addStyle(rand_order, "Quintile metrics", style=pct, cols=c(28:53), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
# addStyle(rand_order, "Median metrics", style=pct, cols=c(28:53), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)
# 
# #accounting format
# addStyle(rand_order, "Quintile metrics", style=acct, cols=c(54:79,106:157), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
# addStyle(rand_order, "Median metrics", style=acct, cols=c(54:79,106:157), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)

saveWorkbook(rand_order, paste0("/data/metrics_", format(Sys.time(), "%d-%b-%Y %H.%M"), ".xlsx"))
```


```{r ptiles merged to CPS with random noise}

quintiles <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(avg_wage_all = weighted.mean(weekpay_rndm, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            n=n())

ptile50 <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(ptile50 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            n=n())

cps_quants <- cps_filtered %>% 
  inner_join(quintiles, by='year') %>% 
  mutate(bins = ifelse(realweekpay <= ptile20, 1,
                       ifelse((realweekpay > ptile20 & realweekpay <= ptile40), 2,
                              ifelse((realweekpay > ptile40 & realweekpay <= ptile60), 3,
                                     ifelse((realweekpay > ptile60 & realweekpay <= ptile80), 4, 5))))) 

cps_medians <- cps_filtered %>% 
  inner_join(ptile50, by='year') %>% 
  mutate(bins = ifelse(realweekpay > ptile50, yes=1, no = 0))


```


```{r ptiles merged to CPS}

quantiles_real <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(avg_wage_all = weighted.mean(realweekpay, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            n=n())

ptile50_real <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(ptile50 = weighted_quantile(realweekpay, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            n=n())

cps_quants_real <- cps_filtered %>% 
  inner_join(quantiles, by='year') %>% 
  mutate(bins = ifelse(realweekpay <= ptile20, 1,
                       ifelse((realweekpay > ptile20 & realweekpay <= ptile40), 2,
                              ifelse((realweekpay > ptile40 & realweekpay <= ptile60), 3,
                                     ifelse((realweekpay > ptile60 & realweekpay <= ptile80), 4, 5))))) 

cps_medians_real <- cps_filtered %>% 
  inner_join(ptile50, by='year') %>% 
  mutate(bins = ifelse(realweekpay > ptile50, yes=1, no = 0))


```

```{r Average hourly wages of employed }
metrics <- cps_quants %>%
  filter(age<65) %>% 
  group_by(year, bins) %>% 
  summarize(avg_hrly_pay = weighted.mean(realwage, w = orgwgt/12, na.rm=TRUE),
            avg_weekpay = weighted.mean(realweekpay, w=orgwgt/12, na.rn=TRUE),
            avg_hrs = weighted.mean(hourslw0, na.rm=TRUE),
            share_positive_hours = mean(phours1, na.rm=TRUE),
            n=n(),
            wgt_n = sum(orgwgt/12),
            cutoffs = max(realweekpay)) %>% 
  pivot_wider(id_cols = year, names_from = bins, values_from = c(avg_hrly_pay, avg_weekpay, avg_hrs, n, wgt_n, cutoffs))# %>% 
  write_csv(here('data/metrics.csv'), col_names = TRUE)

metrics50 <- cps_medians %>%
  filter(age<65) %>% 
  group_by(year, bins) %>% 
  summarize(avg_hrly_pay = weighted.mean(realwage, w = orgwgt/12, na.rm=TRUE),
            avg_weekpay = weighted.mean(realweekpay, w=orgwgt/12, na.rn=TRUE),
            avg_hrs = weighted.mean(hourslw0, na.rm=TRUE),
            share_positive_hours = mean(phours1, na.rm=TRUE),
            n=n(),
            wgt_n = sum(orgwgt/12),
            epop = weighted.mean(emp, w=orgwgt/12, na.rm=TRUE),
            cutoffs = max(realwage)) %>% 
  pivot_wider(id_cols = year, names_from = bins, values_from = c(avg_hrly_pay, avg_weekpay, avg_hrs, n, wgt_n, epop, cutoffs))# %>% 
  write_csv(here('data/metrics2.csv'), col_names = TRUE)

```
