---
title: "R Notebook"
output: html_notebook
---

```{r libraries, include=FALSE}
library(tidyverse)
library(epiextractr)
library(epidatatools)
library(labelled)
library(here)
library(blsAPI)
library(openxlsx)
```

anyhow, don't need to do it all now, but we should definitely grab the data we need sooner rather than later. that's measures of labor market slack (unemployment rate, EPOP, prime-age EPOP) and measures of poverty (overall, under 65, child poverty) nationally and by state, historical series of whatever is possible, 1979, 1989, 1994 as the start date, ideally 1979-2019.


```{r Load data}
states <- read_csv(here('input/state_abbv.csv'), col_names = TRUE)

ind.cps <-load_basic(1979:2019, year, month, basicwgt, orgwgt, age, lfstat, emp, unemp, selfinc, selfemp, statefips) %>% 
  mutate(selfemp0 = ifelse(selfemp==1 & !is.na(selfemp), yes=1, no=0),
         selfinc0 = ifelse(selfinc==1 & !is.na(selfinc), yes=1, no=0))

overall.pov <- read_csv(here('input/overall_poverty.csv'), col_names = TRUE) %>% 
  pivot_longer(-c(state_abbr, state), names_to = 'year', values_to = 'overall_pov') %>% 
  mutate(year = as.integer(year))

child.pov <- read_csv(here('input/child_poverty.csv'), col_names = TRUE) %>% 
  pivot_longer(-c(state_abbr, state), names_to = 'year', values_to = 'child_pov') %>% 
  mutate(year = as.integer(year))

```

```{r Indicators}

### National indicators 

natl.paepop <- ind.cps %>% 
  filter(age>=25 & age<=54) %>% 
  group_by(year) %>% 
  summarize(epop25_54 = weighted.mean(emp, w=basicwgt/12, na.rm=TRUE))

natl.epop <- ind.cps %>% 
  filter(age>=16) %>% 
  group_by(year) %>% 
  summarize(epop = weighted.mean(emp, w=basicwgt/12, na.rm=TRUE))

natl.urate <- ind.cps %>% 
  filter(age>=16, lfstat!=3) %>% 
  group_by(year) %>% 
  summarize(urate = weighted.mean(unemp, w=basicwgt/12, na.rm=TRUE))

natl.indicators <- natl.paepop %>% 
  left_join(natl.epop) %>% 
  left_join(natl.urate)

### State indicators

st.paepop <- ind.cps %>% 
  filter(age>=25 & age<=54) %>% 
  group_by(year, statefips) %>% 
  summarize(epop25_54 = weighted.mean(emp, w=basicwgt/12, na.rm=TRUE)) %>% 
  mutate(statefips = to_factor(statefips)) %>% 
  left_join(states, by=c('statefips'='state_abbr')) %>% 
  relocate(state, .after = statefips)

st.epop <- ind.cps %>% 
  filter(age>=16) %>% 
  group_by(year, statefips) %>% 
  summarize(epop = weighted.mean(emp, w=basicwgt/12, na.rm=TRUE)) %>% 
  mutate(statefips = to_factor(statefips)) %>% 
  left_join(states, by=c('statefips'='state_abbr')) %>% 
  relocate(state, .after = statefips)

st.unemp <- ind.cps %>% 
  filter(age>=16, lfstat!=3) %>% 
  group_by(year, statefips) %>% 
  summarize(urate = weighted.mean(unemp, w=basicwgt/12, na.rm=TRUE)) %>% 
  mutate(statefips = to_factor(statefips)) %>%
  left_join(states, by=c('statefips'='state_abbr')) %>% 
  relocate(state, .after = statefips) 

st.epop_wide <- st.epop %>% 
  pivot_wider(id_cols = c(year), names_from = c(state), values_from = epop)

st.paepop_wide <-st.paepop %>% 
  pivot_wider(id_cols = c(year), names_from = c(state), values_from = epop25_54)

st.unemp_wide <- st.unemp %>% 
  pivot_wider(id_cols = c(year), names_from = c(state), values_from = urate)

st.indicators <- st.paepop %>% 
  left_join(st.epop) %>% 
  left_join(st.unemp) %>% 
  left_join(overall.pov) %>% 
  left_join(child.pov) %>% 
  select(-state_abbr)
  
    
```

```{r Poverty data from SWX}


```



```{r}
indicators <- createWorkbook()

addWorksheet(indicators, sheetName = "Natl. indicators")
addWorksheet(indicators, sheetName = "St. indicators, long")
addWorksheet(indicators, sheetName = "St. unemp")
addWorksheet(indicators, sheetName = "St. epop")
addWorksheet(indicators, sheetName = "St. paepop")


pct = createStyle(numFmt = '0.0%')
acct = createStyle(numFmt = '#.0' )
hs1 <- createStyle(fgFill = "#4F81BD", halign = "CENTER", textDecoration = "Bold",
                   border = "Bottom", fontColour = "white")

writeData(indicators, natl.indicators, headerStyle = hs1, sheet = "Natl. indicators", startCol = 1, startRow = 1, colNames = TRUE)
writeData(indicators, st.indicators, headerStyle = hs1, sheet = "St. indicators, long", startCol = 1, startRow = 1, colNames = TRUE)
writeData(indicators, st.unemp_wide, headerStyle = hs1, sheet = "St. unemp", startCol = 1, startRow = 1, colNames = TRUE)
writeData(indicators, st.epop_wide, headerStyle = hs1, sheet = "St. epop", startCol = 1, startRow = 1, colNames = TRUE)
writeData(indicators, st.paepop_wide, headerStyle = hs1, sheet = "St. paepop", startCol = 1, startRow = 1, colNames = TRUE)


#add percent format
addStyle(indicators, "Natl. indicators", style=pct, cols=c(2:4), rows=2:(nrow(natl.indicators)+1), gridExpand=TRUE)
addStyle(indicators, "St. indicators, long", style=pct, cols=c(4:8), rows=2:(nrow(st.indicators)+1), gridExpand=TRUE)
addStyle(indicators, "St. unemp", style=pct, cols=c(2:52), rows=2:(nrow(st.unemp_wide)+1), gridExpand=TRUE)
addStyle(indicators, "St. epop", style=pct, cols=c(2:52), rows=2:(nrow(st.epop_wide)+1), gridExpand=TRUE)
addStyle(indicators, "St. paepop", style=pct, cols=c(2:52), rows=2:(nrow(st.paepop_wide)+1), gridExpand=TRUE)


saveWorkbook(indicators, here("output/natl_state_indicators.xlsx"), overwrite = TRUE)
```




