---
title: "pov_emp_hours"
author: "Daniel Perez"
date: "12/9/2021"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(epiextractr)
library(epidatatools)
library(labelled)
library(here)
library(blsAPI)
library(openxlsx)
library(MetricsWeighted)
library(gtools)
library(statar)
```


```{r Load CPS}
cpi <- read_csv(here("input/cpi_annual.csv")) 
cpi_base <- cpi$cpiurs[cpi$year == 2019] 

#1994 is the lower bound year since hoursu1i is available 1994-present 
cpsorg <-load_org(1994:2019, year, month, orgwgt, hhid, personid, statefips, age, emp, selfemp, selfinc, hourslw1, hoursu1i, multjobs, lfstat, wage, earnhour) %>%
  filter(age>=16) %>%
  mutate(wgt = orgwgt/12) %>% 
  #create new version of selfemp/selfinc to exclude self employer workers
  mutate(selfemp0 = ifelse(selfemp==1 & !is.na(selfemp), yes=1, no=0),
         selfinc0 = ifelse(selfinc==1 & !is.na(selfinc), yes=1, no=0)) %>% 
  filter(selfemp0==0, selfemp0==0) %>% 
  #Merge CPI-U-RS data
  left_join(cpi, by='year') %>% 
  mutate(realwage = wage*(cpi_base/cpiurs), # inflation adjust wages to 2019$
         realwage0 = replace(realwage, emp==0, 0), #Set unemployed workers' wages to 0
         realweekpay = realwage0 * hoursu1i, #generate a weekly pay variable
         realweekpay0 = replace(realweekpay, emp==0, 0),
         pwages = ifelse(realwage0>0 & !is.na(realwage0) , yes=1, no=0), #create positive wage indicator
         pweekpay = ifelse(realweekpay0>0 & !is.na(realweekpay0) , yes=1, no=0), #create positive weekpay indicator
         hoursu1i = replace(hoursu1i, emp==0, 0), #Set hours to 0 if unemployed
         phours1 = ifelse(hoursu1i>0 & !is.na(hoursu1i), yes=1, no=0)) %>%  #create positive hours indicator
  set_value_labels(pwages = c('Positive wages' = 1, 'Zero wages' = 0),
                   pweekpay = c('Positive weekpay' = 1, 'Zero weekpay' = 0),
                   phours1 = c('Positive hours, primary job' = 1, 'Zero hours' =0))

```

As a note, we want to remove self employed / self incorporated folks because they do not report wages / hours despite being employed. We do want to keep non-self emp/inc folks though, including those who are just NILF or selfemp/selfinc==NA, because we want to turn them into NILF workers with zero wages/hours

```{r Quintile and Median analysis}

set.seed(1017)

cps_filtered <- cpsorg %>% 
  filter(selfemp0==0, selfemp0==0, age<65) %>% 
  filter((emp==1 & phours1== 1 & pweekpay==1) | (emp==0 & phours1==0 & pweekpay==0)) %>% 
  mutate(index = runif(nrow(.), min = 0, max=1)) %>%  #assign each observation a random # between 0 and 1
  arrange(year, realweekpay0, index) %>%  # sort by year, real weekly pay, and index (might be unnecessary)?
  group_by(year) %>% 
  mutate(cumsum = cumsum(orgwgt/12), #column with cumulative sum of org weight
         pop = sum(orgwgt/12), #column with total pop in each year
         quint_pop = pop/5, # 1/5th of the weighted population by year
         med_pop = pop/2) %>% # 1/2 of weighted pop by year
  mutate(quint_bins = ifelse(cumsum <= quint_pop, 1,
                       ifelse(cumsum > quint_pop & cumsum <= quint_pop*2, 2,
                              ifelse(cumsum > quint_pop*2 & cumsum <= quint_pop*3, 3,
                                     ifelse(cumsum > quint_pop*3 & cumsum <= quint_pop*4, 4, 5))))) %>% 
  mutate(med_bin = ifelse(cumsum <= med_pop, yes=1, no=2)) %>% 
  ungroup()

quintile_metrics <- cps_filtered %>% 
  group_by(year, quint_bins) %>% 
  summarize(avg_weekpay = weighted.mean(realweekpay0, w=wgt),
            epop = weighted.mean(emp, w=wgt),
            avg_hours = weighted.mean(hoursu1i, w=wgt),
            avg_wage = weighted.mean(realwage0, w=wgt),
            n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  pivot_wider(id_cols = quint_bins, names_from = year, values_from = c(avg_weekpay, epop, avg_hours, avg_wage, n, wgt_n))


median_metrics <- cps_filtered %>% 
  group_by(year, med_bin) %>% 
  summarize(avg_weekpay = weighted.mean(realweekpay0, w=wgt),
            epop = weighted.mean(emp, w=wgt),
            avg_hours = weighted.mean(hoursu1i, w=wgt),
            avg_wage = weighted.mean(realwage0, w=wgt),
            n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  pivot_wider(id_cols = med_bin, names_from = year, values_from = c(avg_weekpay, epop, avg_hours, avg_wage, n, wgt_n))

```

```{r Workbook export}

rand_order <- createWorkbook()

pct = createStyle(numFmt = '0.0%')
acct = createStyle(numFmt = '#,#0.0')
currency = createStyle(numFmt = '$#,#0.00') 
hs2 <- createStyle(fgFill = "#bfbfbf", halign = "CENTER", textDecoration = "Bold",
                   border = "Bottom", fontColour = "black")

addWorksheet(rand_order, sheetName = "Quintile metrics")
addWorksheet(rand_order, sheetName = "Median metrics")

writeData(rand_order, quintile_metrics, headerStyle = hs2, sheet = "Quintile metrics", startCol = 1, startRow = 1, colNames = TRUE)
writeData(rand_order, median_metrics, headerStyle = hs2, sheet = "Median metrics", startCol = 1, startRow = 1, colNames = TRUE)

#Currency format
addStyle(rand_order, "Quintile metrics", style=currency, cols=c(2:27, 80:105), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
addStyle(rand_order, "Median metrics", style=currency, cols=c(2:27, 80:105), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)

#Percent format
addStyle(rand_order, "Quintile metrics", style=pct, cols=c(28:53), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
addStyle(rand_order, "Median metrics", style=pct, cols=c(28:53), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)

#accounting format
addStyle(rand_order, "Quintile metrics", style=acct, cols=c(54:79,106:157), rows=2:(nrow(quintile_metrics)+1), gridExpand=TRUE)
addStyle(rand_order, "Median metrics", style=acct, cols=c(54:79,106:157), rows=2:(nrow(median_metrics)+1), gridExpand=TRUE)

saveWorkbook(rand_order, here("data/Metrics.xlsx"), overwrite = TRUE)
```


```{r ptiles merged to CPS}

quintiles <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(avg_wage_all = weighted.mean(weekpay_rndm, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            n=n())

ptile50 <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(ptile50 = weighted_quantile(weekpay_rndm, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            n=n())

cps_quants <- cps_filtered %>% 
  inner_join(quintiles, by='year') %>% 
  mutate(bins = ifelse(realweekpay0 <= ptile20, 1,
                       ifelse((realweekpay0 > ptile20 & realweekpay0 <= ptile40), 2,
                              ifelse((realweekpay0 > ptile40 & realweekpay0 <= ptile60), 3,
                                     ifelse((realweekpay0 > ptile60 & realweekpay0 <= ptile80), 4, 5))))) 

cps_medians <- cps_filtered %>% 
  inner_join(ptile50, by='year') %>% 
  mutate(bins = ifelse(realweekpay0 > ptile50, yes=1, no = 0))


```


```{r ptiles merged to CPS}

quantiles_real <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(avg_wage_all = weighted.mean(realweekpay0, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            n=n())

ptile50_real <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(ptile50 = weighted_quantile(realweekpay0, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            n=n())

cps_quants_real <- cps_filtered %>% 
  inner_join(quantiles, by='year') %>% 
  mutate(bins = ifelse(realweekpay0 <= ptile20, 1,
                       ifelse((realweekpay0 > ptile20 & realweekpay0 <= ptile40), 2,
                              ifelse((realweekpay0 > ptile40 & realweekpay0 <= ptile60), 3,
                                     ifelse((realweekpay0 > ptile60 & realweekpay0 <= ptile80), 4, 5))))) 

cps_medians_real <- cps_filtered %>% 
  inner_join(ptile50, by='year') %>% 
  mutate(bins = ifelse(realweekpay0 > ptile50, yes=1, no = 0))


```

```{r Average hourly wages of employed }
metrics <- cps_quants %>%
  filter(age<65) %>% 
  group_by(year, bins) %>% 
  summarize(avg_hrly_pay = weighted.mean(realwage0, w = orgwgt/12, na.rm=TRUE),
            avg_weekpay = weighted.mean(realweekpay0, w=orgwgt/12, na.rn=TRUE),
            avg_hrs = weighted.mean(hourslw0, na.rm=TRUE),
            share_positive_hours = mean(phours1, na.rm=TRUE),
            n=n(),
            wgt_n = sum(orgwgt/12),
            cutoffs = max(realweekpay0)) %>% 
  pivot_wider(id_cols = year, names_from = bins, values_from = c(avg_hrly_pay, avg_weekpay, avg_hrs, n, wgt_n, cutoffs))# %>% 
  write_csv(here('data/metrics.csv'), col_names = TRUE)

metrics50 <- cps_medians %>%
  filter(age<65) %>% 
  group_by(year, bins) %>% 
  summarize(avg_hrly_pay = weighted.mean(realwage0, w = orgwgt/12, na.rm=TRUE),
            avg_weekpay = weighted.mean(realweekpay0, w=orgwgt/12, na.rn=TRUE),
            avg_hrs = weighted.mean(hourslw0, na.rm=TRUE),
            share_positive_hours = mean(phours1, na.rm=TRUE),
            n=n(),
            wgt_n = sum(orgwgt/12),
            epop = weighted.mean(emp, w=orgwgt/12, na.rm=TRUE),
            cutoffs = max(realwage0)) %>% 
  pivot_wider(id_cols = year, names_from = bins, values_from = c(avg_hrly_pay, avg_weekpay, avg_hrs, n, wgt_n, epop, cutoffs))# %>% 
  write_csv(here('data/metrics2.csv'), col_names = TRUE)

```


```{r Sample validation}

#assessment and removal of folks with inconsistent earnings/hours/employment status
phours_pwages_by_empstat_fmt <- cpsorg %>% 
  filter(selfemp0==0, selfinc0==0) %>%
  group_by(year, emp, pwages, phours1) %>% 
  summarize(n = n()) %>% 
  group_by(year) %>% 
  mutate(freq = n/sum(n)) %>% 
  ungroup() %>% 
  filter((emp==1 & phours1== 1 & pwages==1) | (emp==0 & phours1==0 & pwages==0)) %>% 
  mutate(across(pwages|phours1|emp, ~ to_factor(.x)))

phours_pwages_by_empstat_raw <- cpsorg %>% 
  filter(selfemp0==0, selfinc0==0) %>%
  group_by(year, emp, pwages, phours1) %>% 
  summarize(n = n()) %>% 
  group_by(year) %>% 
  mutate(freq = n/sum(n)) %>% 
  ungroup() %>% 
  mutate(across(pwages|phours1|emp, ~ to_factor(.x))) 

phours_pwages_by_empstat_raw_under65 <- cps_filtered %>% 
  filter(selfemp0==0, selfinc0==0, age<65) %>%
  group_by(year, emp, pwages, phours1) %>% 
  summarize(n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  group_by(year) %>% 
  mutate(freq = n/sum(n),
         freq_wgt = wgt_n/sum(wgt_n)) %>% 
  ungroup() %>% 
  mutate(across(pwages|phours1|emp, ~ to_factor(.x))) %>% 
  arrange(year,-n, wgt_n)

phours_pwages_by_empstat_raw_16plus <- cps_filtered %>% 
  filter(selfemp0==0, selfinc0==0, age<65) %>%
  group_by(year, emp, pwages, phours1) %>% 
  summarize(n = n(),
            wgt_n = sum(orgwgt/12)) %>% 
  group_by(year) %>% 
  mutate(freq = n/sum(n),
         freq_wgt = wgt_n/sum(wgt_n)) %>% 
  ungroup() %>% 
  mutate(across(pwages|phours1|emp, ~ to_factor(.x))) %>% 
  arrange(year,-n, wgt_n)

```


```{r Hours and wages with zeros}
hrly_wage0_under65 <- cps_filtered %>%
  filter(age<65) %>% 
  group_by(year) %>% 
  summarize(avg_wage_all = weighted.mean(realwage0, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            ptile99 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.99, na.rm=TRUE),
            share_positive_wages = weighted.mean(pwages, w = orgwgt/12, na.rm=TRUE))# %>% 
  pivot_longer(!c(year,avg_wage_all), names_to = 'wage_quantile', values_to = 'cutoff')

hrly_wage0_16plus <- cps_filtered %>%
  group_by(year) %>% 
  summarize(wages_all = weighted.mean(realwage0, w=orgwgt/12, na.rm=TRUE),
            ptile20 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.20, na.rm=TRUE),
            ptile40 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.40, na.rm=TRUE),
            ptile50 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.50, na.rm=TRUE),
            ptile60 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.60, na.rm=TRUE),
            ptile80 = weighted_quantile(realwage0, w = orgwgt/12, probs = 0.80, na.rm=TRUE),
            share_positive_wages = weighted.mean(pwages, w = orgwgt/12, na.rm=TRUE))

hrs_wgs_under65 <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>%
  mutate(wage_rank = xtile(realwage0, n=5, wt=orgwgt/12)) %>% 
  group_by(year, wage_rank) %>% 
  summarize(wagerank_avg = mean(realwage0, na.rm=TRUE),
            cutoffs = max(realwage0, na.rm=TRUE),
            avg_hrs = mean(hourslw0, na.rm=TRUE),
            n=n())

hrs_wgs_16plus <- cps_filtered %>% 
  group_by(year) %>%
  mutate(wage_rank = xtile(realwage0, n=5, wt=orgwgt/12)) %>% 
  group_by(year, wage_rank) %>% 
  summarize(wagerank_avg = mean(realwage0, na.rm=TRUE),
            cutoffs = max(realwage0, na.rm=TRUE),
            avg_hrs = mean(hourslw0, na.rm=TRUE),
            n=n())

hrs_wgs_under65_wgt <- cps_filtered %>% 
  filter(age<65) %>% 
  group_by(year) %>%
  mutate(wage_rank = xtile(realwage0, n=5, wt=orgwgt/12)) %>% 
  group_by(year, wage_rank) %>% 
  summarize(wagerank_avg = mean(realwage0, na.rm=TRUE),
            cutoffs = max(realwage0, na.rm=TRUE),
            avg_hrs = mean(hourslw0, na.rm=TRUE),
            n=n(),
            wgt_n = sum(orgwgt/12))

hrs_wgs_16plus_wgt <- cps_filtered %>% 
  group_by(year) %>%
  mutate(wage_rank = xtile(realwage0, n=5, wt=orgwgt/12)) %>% 
  group_by(year, wage_rank) %>% 
  mutate()
  summarize(wagerank_avg = mean(realwage0, na.rm=TRUE),
            cutoffs = max(realwage0, na.rm=TRUE),
            avg_hrs = mean(hourslw0, na.rm=TRUE),
            n=n())
```




```{r Hours calculations by state}

epops25_54 <- cpsorg %>% 
  filter(age>=25 & age<=54) %>% 
  mutate(statefips = to_factor(statefips)) %>% 
  group_by(year, statefips) %>% 
  summarize(epop25_54 = sum(emp * orgwgt/12, na.rm=TRUE) / sum(orgwgt/12))
#  pivot_wider(id_cols = statefips, names_from=year, values_from = epop25_54)

epops_16plus <- cpsorg %>% 
  filter(age>=16, year==2019) %>% 
  mutate(statefips = to_factor(statefips)) %>% 
  group_by(year, statefips) %>% 
  summarize(epop_16plus = sum(emp * orgwgt/12, na.rm=TRUE) / sum(orgwgt/12))# %>% 
#  pivot_wider(id_cols = statefips, names_from=year, values_from = epop_16plus)

hours_16plus <- cpsorg %>% 
  filter(age>=16, lfstat==1) %>% 
#  mutate(statefips = to_factor(statefips)) %>% 
  group_by(year) %>% 
  summarize(hourslw_total = weighted.mean(hourslwt,w = orgwgt/12, na.rm=TRUE),
            hourslw_primary = weighted.mean(hourslw1, w=orgwgt/12, na.rm=TRUE))# %>% 
#  pivot_wider(id_cols = statefips, names_from=year, values_from = hours_16plus)

hours25_54 <- cpsorg %>% 
  filter(age>=25 & age<=54) %>% 
  mutate(statefips = to_factor(statefips)) %>% 
  group_by(year, statefips) %>% 
  summarize(hours25_54 = weighted.mean(hourslwt,w = orgwgt/12, na.rm=TRUE))# %>% 
#  pivot_wider(id_cols = statefips, names_from=year, values_from = hours25_54)
  
```


```{r epop workbook}

epophours <- createWorkbook()

addWorksheet(epophours, sheetName = "Epops 16+")
addWorksheet(epophours, sheetName = "Epops 25-54")
addWorksheet(epophours, sheetName = "Avg hours 16+")
addWorksheet(epophours, sheetName = "Avg hours 25-54")
addWorksheet(epophours, sheetName = "Avg wages 16+")
addWorksheet(epophours, sheetName = "Avg wages 25-54")



writeData(epophours, epops_16plus, sheet = "Epops 16+", startCol = 1, startRow = 1, colNames = TRUE)
writeData(epophours, epops25_54, sheet = "Epops 25-54", startCol = 1, startRow = 1, colNames = TRUE)
writeData(epophours, hours_16plus, sheet = "Avg hours 16+", startCol = 1, startRow = 1, colNames = TRUE)
writeData(epophours, hours25_54, sheet = "Avg hours 25-54", startCol = 1, startRow = 1, colNames = TRUE)


saveWorkbook(epophours, here("data/hours_epops.xlsx"), overwrite = TRUE)
```

